name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: vet
      run: go vet $(go list ./...)

    - name: lint
      run: |
        go get -u golang.org/x/lint/golint
        export PATH=PATH:$(go path GOROOT)/bin/
        golint ./...
      env:
        GO111MODULE: off

    - name: test
      run: go test -v -race -cover ./...
